# Позиция лобби
# Игроки телепортируются в лобби при заходе и командой /lobby
lobby:
  # НЕ ТРОГАЙТЕ ЛИНИЮ СНИЗУ
  ==: org.bukkit.Location
  # Имя мира позиции лобби
  world: world
  # Координаты позиции телепортации
  x: 0.0
  y: 100.0
  z: 0.0
  # Поворот позиции телепортации
  yaw: 0.0
  pitch: 0.0

# Миры, защищенные от игроков, кроме игроков с правом 'elobby.modify' и в креативе
protectedWorlds:
  - 'world'

# Локации телепорта игроков из пустоты
# Если телепорт из пустоты не нужен, не добавляйте мир
voidTeleports:
  # Имя мира, который будет проверяться на телепорт из пустоты
  world:
    # Позиция, куда будет телепортирован игрок, если он в пустоте
    # НЕ ТРОГАЙТЕ ЛИНИЮ СНИЗУ
    ==: org.bukkit.Location
    # Имя мира позиции телепортации
    world: world
    # Координаты позиции телепортации
    x: 0.0
    y: 100.0
    z: 0.0
    # Поворот позиции телепортации
    yaw: 0.0
    pitch: 0.0

# Границы миров
# Если граница не нужна, не добавляйте мир
worldBounds:
  # Имя мира, для которого будет установлена граница
  world:
   # Минимальная позиция X
   x1: -9.5
   # Минимальная позиция Z
   z1: -9.5
   # Максимальная позиция X
   x2: 10.5
   # Максимальная позиция Z
   z2: 10.5
   # Позиция для выводной телепортации
   exit:
    # НЕ ТРОГАЙТЕ ЛИНИЮ СНИЗУ
    ==: org.bukkit.Location
    # Имя мира позиции телепортации
    world: world
    # Координаты позиции телепортации
    x: 0.0
    y: 100.0
    z: 0.0
    # Поворот позиции телепортации
    yaw: 0.0
    pitch: 0.0